# NOTE: the current working directory (cwd) will be set to the location of this file!
# directory with markdown content files and resources, relative to cwd
content_dir: content
# templates directory, relative to cwd
templates_dir: templates
# default template file, relative to `templates_dir`
default_template: default.html.jinja2
# output directory, relative to cwd
output_dir: ../docs/demo_site/
# intermediate files directory -- if null, then no intermediate files will be saved
intermediates_dir: ../tests/_temp/demo_site_intermediates
# kwargs to pass to the Jinja2 environment
jinja_env_kwargs: {}
# whether to prettify with bs4
prettify: true
# pandoc formats
pandoc_fmt_from: markdown+smart
pandoc_fmt_to: html
# extra kwargs to pass to pandoc (this will be augmented with `__pandoc__` from the frontmatter of a file)
__pandoc__:
  mathjax: true
# extra globals to pass -- this can be anything
globals_:
  globals_key: some value
  company_name: Lorem Ipsum Technologies
  mission_statement: consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
  industry: dolor sit amet
  contact_email: Lorem-Ipsum-Technologies@not-a-real-website.com
  contact_phone: +99 (111) 111-1111
  hq_address: |
    123 Dolor Sit Avenue
    Amet City, LP 12345
    Consectetur Country
  company_values:
    - Ut enim ad minim veniam
    - Quis nostrud exercitation ullamco
    - Laboris nisi ut aliquip ex ea commodo consequat
  social_media:
    twitter: https://fake-twitter-link.com/loremipsum
    facebook: https://fake-facebook-link.com/loremipsum
    linkedin: https://fake-linkedin-link.com/company/loremipsum
  founding_year: 2030
  employee_count: 256
  main_services:
    - Duis aute irure dolor in reprehenderit
    - Voluptate velit esse cillum dolore
    - Fugiat nulla pariatur
  company_slogan: Excepteur sint occaecat cupidatat non proident